### ISSUE TITLE
Redirecting to success page

### ISSUE THREAD

**Issue by abbeyseto** [ibrahimlawal/magento2-Profibro_Paystack#24] opened 2018-10-15 19:53 UTC
Hello, i'm sorry i had to comment on this issue. I still have a problem redirecting to success page while testing. After a payment, i see A transaction successful pop up and it disappears but the page page remains the same. It is not redirected to success page.

Magento ver. 2.26
Paystack: Magento2.1 plugin (installed using composer)
PHP Version: 7.1
Server: Linux on Google Compute engine

_Originally posted by @abbeyseto in https://github.com/PaystackHQ/paystack-magento2/issue_comments#issuecomment-429990057_

**Comment by steveamaza** [comment] 2018-11-02 10:21
Duplicate of #6

**Closed as completed by steveamaza** 2018-11-02 10:21 UTC

**Comment by sheyinn** [comment] 2018-11-21 18:34
Hello,

I'm also experiencing the same issue: 400 (bad request). Can someone share a working fix here? I've looked through the thread and haven't found one.
